### ISSUE TITLE
🐞 Extreme Sound Muffler causing a crash on launching worlds

### ISSUE THREAD

**Issue by HauntedToast** [LeoBeliik/ExtremeSoundMuffler#38] opened 2022-02-14 06:33 UTC
### Extreme sound muffler version

3.22

### Forge / Fabric version

Forge 39.0.75

### Describe the bug

When I put up my anchor near my base for bee sounds and villager sounds and then logged off the server, the next time I logged back on the game kept crashing. I asked many mod developers and even forge themselves and eventually the mahou tsukai mod dev told me it was ESM causing my player to load as null. Once I uninstalled the mod, I was able to load into worlds again. 

### Steps to reproduce

1. Load a world
2. Set an anchor near spawn point with radius of 64
3. Set the sounds of bee ambient and villager ambient to 0 and around 10, respectively.
4. Log out of world and try to join back

### Crashlog

https://pastebin.pl/view/9633f9b6

### Additional context

Log:
https://pastebin.pl/view/310fa40f

**Comment by LeoBeliik** [comment] 2022-02-14 07:45
I can't reproduce this, could you send me your ESM folder? it should be inside your pack folder, also could you test this with ESM 3.23?

**Comment by HauntedToast** [comment] 2022-02-14 17:35
https://www.mediafire.com/folder/dvt1htroqbxc6/ESM

**Comment by HauntedToast** [comment] 2022-02-15 19:43
Can you look into this

**Comment by LeoBeliik** [comment] 2022-02-15 19:48
It was not fixed with the update?

**Comment by HauntedToast** [comment] 2022-02-18 06:36
Updating to the most recent version fixed the issue and I was able to join my server, but as soon as I clicked anchor 0 to edit it, my game immediately crashed. 

Crash Report:
https://pastebin.pl/view/7913feae
Log:
https://pastebin.pl/view/4f667965

**Comment by LeoBeliik** [comment] 2022-02-18 06:41
Hmm, try deleting your ESM folder

**Comment by HauntedToast** [comment] 2022-02-18 06:41
https://www.mediafire.com/file/ykmnrtajj75k1gk/latest.log/file
 
Alternate way of looking at log since pastebin is glitching

**Comment by HauntedToast** [comment] 2022-02-18 06:42
> Hmm, try deleting your ESM folder

Will that just cause a new folder to be created on launch

**Comment by LeoBeliik** [comment] 2022-02-18 06:45
yes, but the files will be empty, and if that works, it probably was because the current files are somehow corrupted

**Comment by LeoBeliik** [comment] 2022-02-18 06:50
I can't download the `111 Gang Gang` folder in the link you sent me before, is that the name of the world you're having problems with?

**Comment by HauntedToast** [comment] 2022-02-18 06:53
I deleted the folder and restarted MC and am in the server again. Can I edit an anchor now or should I not?

**Comment by LeoBeliik** [comment] 2022-02-18 06:54
yes, try using the anchors

**Comment by HauntedToast** [comment] 2022-02-18 07:02
Everything works fine. Thank You. I will keep you updated if anything else occurs

**Comment by LeoBeliik** [comment] 2022-02-18 07:05
I'm honestly not sure how this could happen, but glad it was solved!

**Closed as completed by LeoBeliik** 2022-02-18 07:05 UTC
Labels: bug
